halkity/fleamarket_sample_79d

- README.md
DB設計をReadmeに書いた
DB設計をすることにより、機能を付けていくに当たって想像しながら進みやすいから
> [WIP] Readme function

- Gemfile
- Gemfile.lock
- config/environments/development.rb
N+1問題の自動摘出ツールの導入
N+1問題を自動摘出してもらい、解決できるようにするため
> gem 'bullet'の導入

- README.md
- app/models/item.rb
- db/migrate/20200722101010_create_items.rb
- db/schema.rb
- spec/factories/items.rb
- spec/models/item_spec.rb
- test.drawio
itemのモデルを作成し
itemのマイグレーションを外部キー以外作成した
> Updated create-model-item 1st time

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_show.scss
- app/controllers/items_controller.rb
- app/views/items/show.html.haml
- config/routes.rb
商品のshowのビューをメルカリを元に作成した
他の要素(category model, image model, comment modelなど)が不完成な為、大枠のみ作成した。
トップページの作成は同時進行中なので, layoutが出来次第headerとfooterが後々showのビューに追加される
showのビューを先に作成し、レイアウト構成を完成させる為
> [WIP] Updated show-function-item 1st time

- app/assets/stylesheets/items.scss
- app/assets/stylesheets/modules/_index.scss
- app/views/items/index.html.haml
・出品ボタンのレイアウトを作成
・newアクションへのリンク付け
・常に右下に表示されるように固定
> indexページに出品ボタンを追加

- Gemfile
- Gemfile.lock
- app/models/item.rb
- app/models/user.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20200724095054_devise_create_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
usersテーブルとuserモデルを作成し、バリデーションをかけました。
dbとmodelだけで一度LGTMをもらい、フロントとサーバーサイドで分かれて作業を行うため。
> usersテーブルの作成とuserモデルを作成

- app/assets/stylesheets/modules/_index.scss
- app/models/address.rb
- app/models/user.rb
- db/migrate/20200728053701_create_addresses.rb
- db/schema.rb
- spec/factories/addresses.rb
- spec/models/address_spec.rb
- test.drawio
addressテーブルとモデルを作成した。
アソシエーションとバリデーションをaddress.rbに記載
ウィザード形式のユーザー登録の次の段階で、addressのデータベースとモデルが必要なため。
> addressテーブルとモデルの作成・アソシエーションを追加

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_mypage.scss
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/views/items/index.html.haml
- app/views/users/show.html.haml
- config/routes.rb
- spec/helpers/users_helper_spec.rb
- spec/requests/users_request_spec.rb
マイページのビューの大枠を作成した
まだ、imageテーブルなどが作られていないので画像は仮置きしてある
追加の機能により埋める可能性があるボックスも四つ置いてある
マイページの大枠が出来ることにより、データが完成した時に表示しやすくなるため
> Updated device_mypage 1st time

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_destroy.scss
- app/controllers/items_controller.rb
- app/views/items/destroy.html.haml
- app/views/items/show.html.haml
- config/routes.rb
削除機能の追加をした。削除されたら画面が切り替わるようにした。
商品の削除を行うため。
> Destroy fanction item

- app/views/devise/passwords/edit.html.haml
- app/views/devise/passwords/new.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/registrations/new_address.html.haml
- app/views/devise/shared/_links.html.haml
- db/schema.rb
アドレス 入力のレイアウトを作成
アドレスのフロントをおわらすことでサーバーサイドとあとで試しやすくなるから
> Address layout

- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/modules/_show.scss
- app/controllers/comments_controller.rb
- app/controllers/items_controller.rb
- app/helpers/comments_helper.rb
- app/models/comment.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/show.html.haml
- config/routes.rb
- db/migrate/20200730023136_create_comments.rb
- db/migrate/20200730113532_add_prefecture_id_to_items.rb
- db/schema.rb
- spec/factories/comments.rb
- spec/helpers/comments_helper_spec.rb
- spec/models/comment_spec.rb
- spec/requests/comments_request_spec.rb
コメントが一覧表示されるようにした。
商品詳細ページのビューを整えた。
商品の編集ができるようになった。
コメントが見れることで相手と駆け引きできる。
値段の交渉などやりとりできる
> Items show page layout 

- README.md
- app/controllers/users/registrations_controller.rb
- app/models/address.rb
- app/models/prefecture.rb
- app/views/devise/registrations/new_address.html.haml
- db/migrate/20200730033614_remove_prefectures_to_addresses.rb
- db/migrate/20200730034903_add_prefecture_id_to_addresses.rb
- db/migrate/20200730073532_change_datatype_postal_code_of_addresses.rb
- db/migrate/20200730084244_change_datatype_phone_number_of_addresses.rb
- db/schema.rb
- test.drawio
ウィザード形式で前ページのユーザー登録のデータをセッションで保持しつつ、住所登録と合わせてデータを保存するサーバーサイドの実装を行なった。
カード情報の登録は別ページで行い、ひとまずユーザーの新規登録はこれで終了なため。
> ウィザード形式での住所登録のサーバーサイド実装

- README.md
- app/assets/stylesheets/modules/_new.scss
- app/controllers/items_controller.rb
- app/javascript/category.js
- app/models/image.rb
- app/models/item.rb
- app/views/items/new.html.haml
- db/migrate/20200729121301_add_prefecturename_to_items.rb
- db/schema.rb
- db/seeds.rb
・カテゴリー登録機能
・画像登録機能の追加（試験的に２画像のみ）
・その他の購入機能等を進めれるように、出品機能の登録機能を整理した。
・jQueryを用いた画像のプレビュー機能や登録機能は未完成→別branchで行う
> 出品機能にカテゴリー登録機能を追加

- app/assets/stylesheets/modules/_show.scss
- app/controllers/items_controller.rb
- app/views/items/new.html.haml
- app/views/items/show.html.haml
- db/schema.rb
ログインしている人のみコメントが見れる。
出品したユーザーのみ編集と削除ができる。
見た目の修正。
誰でもできないようにするため。
> Only logged in users can see it in show-page

- app/assets/stylesheets/modules/_show.scss
- app/controllers/items_controller.rb
- app/javascript/category.js
- app/views/items/show.html.haml
> items show  modification

- app/views/items/show.html.haml
カテゴリーが親、子、孫の順で表示されるようになった。
ユーザーがみやすいようにするため。
> Items show category indicate

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_done.scss
- app/views/purchase/done.html.haml
> purchase done views

- app/assets/stylesheets/modules/purchase.scss
- app/views/purchase/index.html.haml
> purchase index view layout

- app/controllers/items_controller.rb
- app/models/item.rb
- app/models/period.rb
- app/views/items/_form.html.haml
- app/views/items/show.html.haml
- db/migrate/20200806111923_rename_period_column_to_items.rb
- db/schema.rb
アクティブハッシュを用いての発送日の目安の記述
変わることのないデータのため
> Items show view image date

- app/models/comment.rb
- app/models/image.rb
- app/models/item.rb
- app/views/items/index.html.haml
- spec/controllers/items_controller_spec.rb
- spec/factories/addresses.rb
- spec/factories/categories.rb
- spec/factories/items.rb
- spec/factories/users.rb
- spec/models/address_spec.rb
- spec/models/item_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
ユーザー登録・アドレス登録の単体テスト
items_controllerのテストコードを実装
新規登録・商品出品の一部のテストコードを実装することにより、バリデーションが正しくなっているか、正しい値が飛んでいるかの確認を行うため。
> [WIP] ユーザー・アドレス・items_controllerのテストコード

- app/assets/stylesheets/modules/_show.scss
- app/uploaders/image_uploader.rb
- app/views/items/show.html.haml
画像を読み込めるようにした。
枚数が３枚以上になったら下に表示されるようにした。（flexwrap)
##Why
画像を見て選ぶことができるため。
> items show image load

- app/assets/stylesheets/modules/_flash.scss
・フラッシュメッセージ のデザイン修正
・フラッシュメッセージが見えにくかったため修正した
> フラッシュメッセージのレイアウト修正

- app/models/item.rb
- app/views/items/_form.html.haml
- app/views/items/show.html.haml
> items show correction(修正)

- app/models/item.rb
画像ごと削除できるようにした。
画像と結びついていたので削除できなかったため。
> items destroy confirmation

- app/assets/stylesheets/modules/_mypage.scss
- app/controllers/users_controller.rb
- app/views/users/show.html.haml
マイページの画像をeachメソッドで出力するようにした
ユーザーが自分んお投稿をまとめて見るため
> [WIP] Updated mypage-function-adjustment

- app/controllers/purchase_controller.rb
- app/models/item.rb
> Purchase controller fix

- app/controllers/items_controller.rb
出品エラー処理後、ビューにinputボタンが表示されなくなるエラーを解決
> 出品エラー処理後のエラー解決

- app/views/items/show.html.haml
> items show explanation
